### ISSUE TITLE
`run.py` do not support multi-gpu training

### ISSUE THREAD

**Issue by TIANRUI981107** [talbenha/cell-tracker-gnn#12]
hi,

I was trying this project on a new dataset, but it turns out that the `run.py` script doesn't support multi-gpu training. 

May I know where I can change for multi-gpu training?

Thanks for you help!

**Comment by talbenha** [comment]
hi @TIANRUI981107 , why do you need multi-gpu training? the code can be run on single gpu without any problem 
anyway consider Distributed Data Parallel (DDP) strategy to do so https://lightning.ai/docs/pytorch/stable/accelerators/gpu_intermediate.html

**Comment by R-Tian1** [comment]
> hi @TIANRUI981107 , why do you need multi-gpu training? the code can be run on single gpu without any problem anyway consider Distributed Data Parallel (DDP) strategy to do so https://lightning.ai/docs/pytorch/stable/accelerators/gpu_intermediate.html

Hello, and thanks for your response!

I wanna use multi-gpu training in `run.py` because it will throw me an `out-of-memory` error when the `batch_size` params in `./configs/datamodule/datamodule_multiSequence.yaml` was set larger than 2.

Given the numerous objects in my datasets (~200 objects/frame) that need to be tracked, it would be more appropriate for me to use a larger batch_size :-)

I'll try for the DDP strategy and see if I can make it for a pull request.

**Comment by talbenha** [comment]
hi @TIANRUI981107 , 
Do you have an update if you manage to run on multi-gpu? 

I'm closing the issue for now. If you have a question and want to continue the discussion please let me know and I will re-open it.
